### ISSUE TITLE
Removing tildes

### ISSUE THREAD

**Issue by alok** [MitMaro/git-interactive-rebase-tool#112]
When I run the tool, I notice that there are tildes on the left margin like in vim. This is very much an aesthetic thing, but ever since vim let me remove those tildes, I've pursued their eradication in any program I use. They seem to be drawn in `view.rs` on line 250.

In the case of this tool, I don't see the benefit to them since they add visual clutter and don't help you find your current line since there's a little pointer for that already.

**Comment by MitMaro** [comment]
That's a fair criticism and as you state they are purely cosmetic. I initially added them to aid in debugging but liked their appearance so kept them in.

It should be easy to make the character configurable so that it can be easily set to an empty character to not show it.

**Comment by alok** [comment]
I think I've just been traumatized by the squiggles since they silently mocked me when I was first struggling with vim. (Though now I use it for everything. I considered it a sign I'd become proficient when I could configure it enough to remove them.)

**Comment by MitMaro** [comment]
You can now set the character to an empty string in the configuration and it will be removed.

Thanks for the input!
