### ISSUE TITLE
Visual mode missing from help text

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#125]
The help text is currently missing a keybinding for visual mode.

See also: https://github.com/MitMaro/git-interactive-rebase-tool/blob/fda60a2d767544f1482181c5eeb69616f82703fc/src/constants.rs#L33-L55

**Comment by MitMaro** [comment]
Thanks for the report! The next release will have this fixed.

**Comment by MitMaro** [comment]
Turns out I missed fixing this in the above PR. Thanks @whymarrh for bringing it to my attention.
