### ISSUE TITLE
Show commit diff/patch

### ISSUE THREAD

**Issue by dwijnand** [MitMaro/git-interactive-rebase-tool#126]
It would be nice if, in addition to the commit information, the commit's diff/patch were shown.

**Comment by MitMaro** [comment]
This is something I've been wanting to add for a while now and really want the feature. It's similar to pull request #57 , but I think would be more useful.

**Comment by MitMaro** [comment]
I've been picking away at this feature for some time now. I currently have the commit diff loaded into a data structure that can be displayed. I just need to write the display logic. Here's a screenshot of the progress so far:
![Screenshot from 2020-03-07 20-13-04](https://user-images.githubusercontent.com/177427/76154046-5385a700-60b0-11ea-924c-0cd783b127c2.png)

**Comment by MitMaro** [comment]
I've had to do a lot of refactoring to get to this point, but I'm getting close to having a diff view working. I am working on adding configuration values for some currently static values.

Here's how things look as of tonight:

![Screenshot from 2020-07-05 21-44-46](https://user-images.githubusercontent.com/177427/86545371-0653fd80-bf09-11ea-807e-7026892ad6d5.png)

**Comment by MitMaro** [comment]
After literally months of work, a full refactor of the render system and hitting my head against the git2-rs library I have pushed a diff view tonight. :laughing: 

It's also fairly configurable and respects most of the existing git config settings. Things like showing whitespace characters, tab width, tab symbol, space symbol are all configurable along with the general theme and keybindings. 

I will still need to test this on MacOS and Windows before doing a release, but I hope that will not take too long!

Some screenshots:

#### General diff view
![Screenshot from 2020-07-26 21-28-35](https://user-images.githubusercontent.com/177427/88492672-fe76fe80-cf86-11ea-92da-e377e9ba6026.png)

#### Missing newline support
![Screenshot from 2020-07-26 21-24-38](https://user-images.githubusercontent.com/177427/88492634-a50ecf80-cf86-11ea-80a2-4640088c02dc.png)

#### Leading and trailing whitespace support
![Screenshot from 2020-07-26 21-27-45](https://user-images.githubusercontent.com/177427/88492663-ea330180-cf86-11ea-8941-774a152e6a3e.png)

**Comment by dwijnand** [comment]
That's awesome, thank you!
