### ISSUE TITLE
'Could not execute editor' for noop rebases

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#138]
Similar to #4 but it doesn't panic now. A noop rebase produces a error message and a non-zero exit code:

```
eth-faucet (master=) $ git rebase -i master 
Nothing to rebase
Could not execute editor
```
```
eth-faucet (master=) $ GIT_SEQUENCE_EDITOR=vim git rebase -i master 
Successfully rebased and updated refs/heads/master.
```
```
eth-faucet (master=) $ git rebase -i master 
Nothing to rebase
Could not execute editor
```
```
eth-faucet (master=) $ echo $?
1
```
```
eth-faucet (master=) $ GIT_SEQUENCE_EDITOR=vim git rebase -i master 
Successfully rebased and updated refs/heads/master.
```
```
eth-faucet (master=) $ echo $?
0
```

The contents of the `git-rebase-todo` file:

```
noop

# Rebase 308ad5a..308ad5a onto 308ad5a (1 command)
#
# Commands:
# p, pick = use commit
# r, reword = use commit, but edit the commit message
# e, edit = use commit, but stop for amending
# s, squash = use commit, but meld into previous commit
# f, fixup = like "squash", but discard this commit's log message
# x, exec = run command (the rest of the line) using shell
# d, drop = remove commit
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

**Comment by MitMaro** [comment]
@whymarrh What would you expect to be the general use case for a `noop` rebase? Should the tool immediately exit with a proper status code of 0 or should the tool show the list of commits with only the `noop` operation?

**Comment by whymarrh** [comment]
> Should the tool immediately exit with a proper status code of 0 or should the tool show the list of commits with only the noop operation?

Either works, I'd say. Vim opens with single `noop` line, but that's not _super_ helpful. I'd think exiting with 0 and maybe displaying a message (if the terminal is interactive) along the lines of "Completed successful noop rebase.

> What would you expect to be the general use case for a noop rebase?

When somebody makes a mistake.

**Comment by MitMaro** [comment]
Thanks @whymarrh . That shouldn't be too bad to implement.
