### ISSUE TITLE
Change j/k key bindings

### ISSUE THREAD

**Issue by jonashaag** [MitMaro/git-interactive-rebase-tool#142]
Problem: As a vim user I will intuitively try to move the cursor using j/k rather than with the arrow keys. There's not a lot of visual feedback when you reorder commits (except for the fact that the actual order is changed), which results in accidental commit reordering. Happened to me multiple times now. It's difficult to unlearn muscle memory.

My suggestion is to change this to Shift+j/k. Reordering commits should be an action that "feels a bit more heavyweight" than just pushing j/k IMO. Then you can make j/k an alias for arrow keys.

**Comment by MitMaro** [comment]
Hey @jonashaag !

I actually have rebinding keys working in a local branch that I am planning to get in for the next release that will allow you to do exactly this. I will update this issue once it's released!

**Comment by MitMaro** [comment]
Custom key bindings will be in the next release. Thanks for the request!

**Comment by tpoliaw** [comment]
Just been tripped up by this as well. Making them configurable is a usable workaround but is it worth changing the defaults? j/k doing different things to up/down was really surprising behaviour.
