### ISSUE TITLE
Highlight the selected commit(s) with a background color

### ISSUE THREAD

**Issue by StephenGregory** [MitMaro/git-interactive-rebase-tool#148]
If I have selected commit(s), have them highlighted to distinguish them from unselected rows (think: vim visual model).

**Comment by MitMaro** [comment]
Shouldn't be too bad to implement behind a configuration toggle.

**Comment by MitMaro** [comment]
I looked into this and it's tricky. I need to redo how colours are handled in the application first to support more than 8 color pairs.
