### ISSUE TITLE
deb package: missing dependency

### ISSUE THREAD

**Issue by peppsac** [MitMaro/git-interactive-rebase-tool#170]
Hi,

After installing git-interactive-rebase-tool_1.1.0_amd64.deb the /usr/bin/interactive-rebase-tool will not start due to a missing dependency on the `libncursesw5` package.

```sh
$ ldd /usr/bin/interactive-rebase-tool
	linux-vdso.so.1 (0x00007ffdfccb1000)
	libncursesw.so.5 => /lib/x86_64-linux-gnu/libncursesw.so.5 (0x00007f4b00863000)
	libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f4b00836000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4b00819000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4b00814000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4b00809000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4b007e8000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4b007cc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4b0060c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4b00c69000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4b004c7000)
```

```sh
$ dpkg -S /lib/x86_64-linux-gnu/libncursesw.so.5
libncursesw5:amd64: /lib/x86_64-linux-gnu/libncursesw.so.5
```

Thanks!

**Comment by MitMaro** [comment]
Well that's annoying...

I was hoping that ncurses would be statically linked, but from my research there are reasons it shouldn't be.

All the same, the generated deb file should have picked up that `libncursesw5` was a dependency and added it, but it seems to have not done so. I will have to investigate.

Thanks for bringing this to my attention!

**Comment by MitMaro** [comment]
Well that was a short investigation. Seems at some point I hard coded the dependencies in `Cargo.toml` to `depends = "libncurses5 (>= 6), libgcc1 (>= 1:6), libtinfo5 (>= 6), zlib1g (>= 1:1), libc6 (>= 2)"`.

I will look at removing the hard coding and producing a proper build.

**Comment by MitMaro** [comment]
I've decided to fix this in the upcoming release instead of fixing the existing release. 

Thanks again for reporting the issue!
