### ISSUE TITLE
Editor with command line fails

### ISSUE THREAD

**Issue by mrexodia** [MitMaro/git-interactive-rebase-tool#190]
On my machine I have:

```
core.editor="C:/Program Files (x86)/GitExtensions/GitExtensions.exe" fileeditor
```

When pressing `!` to edit the file there is an error (and a matching TODO). On my Windows-only fork I fixed it like this:

https://github.com/mrexodia/git-interactive-rebase-tool/blob/6d6b917add89702a78740af9a7294ab02e64b0ab/src/external_editor/external_editor.rs#L65-L79

**Comment by MitMaro** [comment]
Thanks for the report @mrexodia !

I believe this should be working with the master version, though I haven't tested it heavily on Windows yet.

I am going to close this issue for now, but if you feel that the current master please reopen with some more details on what doesn't work.
