### ISSUE TITLE
Underline is not working on Windows

### ISSUE THREAD

**Issue by mrexodia** [MitMaro/git-interactive-rebase-tool#191]
The ncurses library does not seem to work. Instead of underlining it uses the useless blue color (which is unreadable) and the inverted background doesn't work. Fix [here](https://github.com/mrexodia/git-interactive-rebase-tool/commit/39c0f3cc9764f382ed3557ccbc804e16daf10652).

![image](https://user-images.githubusercontent.com/2458265/68697653-91017a00-057f-11ea-8481-75d8f068ceb6.png)

**Comment by MitMaro** [comment]
Well that's annoying. Thanks for the report!

**Comment by MitMaro** [comment]
Did some digging into this issue. The Windows Command Prompt does have support for underlining text, it just choose to treat any underlined text as URIs and make them blue. This is true for CMD, PowerShell and GitBash.

Your solution @mrexodia of disabling the underline for Windows looks like the only viable solution. I have things fixed locally and should be able to get a fix up soon.

**Comment by mrexodia** [comment]
Thanks for the updates! I'll check it once I'm back from vacation and have a Windows machine again to test...
