### ISSUE TITLE
Visual select off-by-one when starting at the bottom

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#195]
Pictured below, using visual mode to do a multiple select starting at the bottom of a set of commits and selecting an option (e.g. `f`) does not apply the selection to the last commit. Bottom-up is the issue, apparently, as top-down seems to work fine.

<img width="100" alt="" src="https://user-images.githubusercontent.com/1623628/69767316-4161a780-1156-11ea-85cd-8a4a68cf1781.png">

**Comment by MitMaro** [comment]
I believe this has been fixed in master already in 813b6903f36463cb5768f2014b829acff0d584c9.

**Comment by whymarrh** [comment]
Oh, nice! I'll just wait patiently for the next release, thanks!

**Comment by MitMaro** [comment]
Confirmed that this is fixed in latest master. Thanks for the report @whymarrh!

**Comment by whymarrh** [comment]
No rush; when will this be available in a published release?

**Comment by MitMaro** [comment]
Well, Windows 8 is end of life on January 10, 2023, and I've been holding out until then so I can fully drop support for it. :laughing: 

In all seriousness, I'm working on getting a release out over the next week, but I can't promise anything.

I need to get #196 and #197 fixed first.

I just moved the build over to GitHub actions, which has been the biggest hold back. TravisCI had a 20 minute build which was slowing down things.
