### ISSUE TITLE
Quitting produces a non-zero exit code

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#226]
Quitting a rebase results in a non-zero exit code (`1`). I believe it should be a zero.

By example:

```bash
$ git rebase -i upstream/develop # and quit using ⇧Q
error: nothing to do
$ echo $?
1
```

While providing an empty file produces a zero exit code:

```bash
$ interactive-rebase-tool /dev/null
An empty rebase was provided, nothing to edit
$ echo $?
0
```

Nothing to do shouldn't be an error case, especially when it is a result of intentional user-action.

Edit: I'm using 1.2.1:

```
$ interactive-rebase-tool --version
interactive-rebase-tool 1.2.1
```

**Comment by whymarrh** [comment]
Also thanks again for this tool, I've been using it all day and it greatly improves my workflow ❤️

**Comment by MitMaro** [comment]
> Also thanks again for this tool, I've been using it all day and it greatly improves my workflow heart

Very much welcome! I am glad it improves your workflow! :)

As for the bug report, that status code is returned by Git when an empty TODO file is written, which is the recommended way to abort a rebase. So I don't think there is no way to fix it from within the tool.

```
❱ GIT_SEQUENCE_EDITOR=vim git rebase -i @~1
error: nothing to do
❱ echo $?
1

**Comment by MitMaro** [comment]
I'm going to close this, as I don't think there is anything that can be done. I am open to possible solutions however!

Please feel free to re-open if there are any additional details that I may have overlooked.

**Comment by whymarrh** [comment]
Oh, gotcha, the file is written and Git exits. Yeah, this isn't your bug—thanks for looking into it.
