### ISSUE TITLE
Add shift+v to enter visual mode

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#234]
It's pretty much in my muscle memory that in vim I used to `shift+v` and hit `d` to delete a chunk of commits.

shouldn't be hard to add 'V' hotkey to do the same as 'v'

**Comment by MitMaro** [comment]
This should already be partially possible by changing the key binding using:

```
git config --global interactive-rebase-tool.inputToggleVisualMode V
```

It's not currently possible to have two characters perform the same action however.

**Comment by MitMaro** [comment]
The next release will allow for multiple key bindings to be set. This means that `Shift+v` can be combined with `v` for entering "visual mode".
