### ISSUE TITLE
Hotkey request: add behavior to ENTER key to show commit details

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#235]
The 'c' is nice, but I'd like to see the fuller diff. perhaps with "enter" key?

currently, I have to open another terminal to do `git diff` to see what the commit changes were.

**Comment by glensc** [comment]
Diff view is here:
- https://github.com/MitMaro/git-interactive-rebase-tool/issues/126

so I'm re-titling that I'm requesting enter hotkey to have behavior

**Comment by MitMaro** [comment]
Thanks for the request @glensc !

I believe enter is already partially supported but there is no way to use it in the configuration. Should be fairly easy to add.

If you are interested in taking a look yourself I believe that adding an "enter" to "Enter" mapping in the match in this configuration parser https://github.com/MitMaro/git-interactive-rebase-tool/blob/master/src/config/utils.rs#L8 would work. Enter is already supported in the input handler (https://github.com/MitMaro/git-interactive-rebase-tool/blob/master/src/input/input_handler.rs#L92) so it should just work from there.

**Comment by glensc** [comment]
🚧 Never link to branches 🚧
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker

ps: edit your post

**Comment by MitMaro** [comment]
Good point! Fixed.

**Comment by MitMaro** [comment]
Enter along with as many other special character keys has been added and will be in the next release. Thanks for the request!
