### ISSUE TITLE
Add search functionality and hotkey

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#237]
Coming from vim, I really missing search functionality:

- search for commit id
- search for commit message

I would expect this to be activated like in vim: `/` hotkey and behave like `hlsearch` enabled

If I'm reading screenful of commits (don't ask why), I find my fingers type faster to find commit I'm interested in by search than visual grep (👀) for the commit

**Comment by MitMaro** [comment]
I really like this idea and I wish I had thought of it myself!

**Comment by MitMaro** [comment]
Search from within the list view was added in #797. I haven't added screenshots to the README yet, but in development, `/` starts a search, `Enter` "finishes" the search, then `n` and `N` move between search results.

I tried to keep the default key-bindings and behaviour similar to vim.

I've been working on this for so long, that I forgot there was an issue open for it. 😅

I'm hoping to do a release early in the new year, that will contain this functionality.
