### ISSUE TITLE
Add range selection using arrow keys and holding command

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#24]
For example, in the following gif, I want to be able to press and hold `r` and use my arrow keys to select a range of commits. I think that'd be neat.

![An example of the press-and-hold behaviour](https://cloud.githubusercontent.com/assets/1623628/23670322/e607e1bc-0341-11e7-965e-692678ef45e7.gif)

**Comment by MitMaro** [comment]
I like the idea. Implementation might be interesting though.

**Comment by stevep1983** [comment]
I've played around with this for a bit while learning Rust. I'm under the impression that this is not possible with ncurses. While the approach given [here](https://gamedev.stackexchange.com/a/144966) is promising, it doesn't seem to work in practice.

```
#include <ncurses.h>
  
int main(int argc, char **argv) {
    WINDOW *w = initscr();
    cbreak();               // disable console line buffering
    nodelay(w, TRUE);       // use non-blocking getch()
    noecho();               // don't echo keypresses
    curs_set(FALSE);        // disable the cursor
    clear();                // clear the screen

    char k;

    printw("Q to quit\n");
    while(1) {
        while((k=getch()) != ERR) {
            if(k=='Q') { endwin(); return 0; }
            printw("%c ", k);
        }
    }

    return 0;
}

```

In this demo, I am holding down 4 keys at once. It seems as though the auto-repeat setting of the keyboard in the underlying X session only sends the last keypress repeatedly.

![peek 2018-08-13 17-53](https://user-images.githubusercontent.com/20347119/44056125-e0c991dc-9f21-11e8-8cb7-2e88f53cf101.gif)

The stackexchange link seems to imply that repeatedly calling getch() should retrieve all of the buttons that are held down in sequence. Perhaps this behavior is OS dependent.

**Comment by srl295** [comment]
select-all would be nice also

**Comment by nickolay** [comment]
I sometimes need to _move_ multiple commits as a group, and holding "j" won't work very well :)

Perhaps this could be a two-step process - first select the commits, then apply an action to all of them? Somewhat like vim's `V`isual selection.

**Comment by nickolay** [comment]
https://github.com/nickolay/git-interactive-rebase-tool/pull/1 implements the solution suggested above (I've put it in a separate repo for now because it wouldn't merge cleanly with my another PR). Would appreciate feedback on this.
