### ISSUE TITLE
Double character output on master is broken

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#259]
# Description

On the master build (and possibly currently stable) double width characters such as the 📦 character causes a misalignment of the text. This is because they are rendered as a single character when they display as two.

## TODO file

```
pick aaaaaaa Okay commit message
pick bbbbbbb foo 📦 bar
```

**Comment by whymarrh** [comment]
> and possibly currently stable

Can confirm this is broken on stable:

```
$ interactive-rebase-tool --version
interactive-rebase-tool 1.2.1
```

Screenshot:

<img width="864" alt="" src="https://user-images.githubusercontent.com/1623628/87880320-60ee5e80-c9cb-11ea-8c97-8fd4c4fc050d.png">
