### ISSUE TITLE
Update gif in README to show new diff view feature

### ISSUE THREAD

**Issue by jackharrhy** [MitMaro/git-interactive-rebase-tool#263]
#262 is _nice_, and should be shown off in the README 👍

**Comment by MitMaro** [comment]
I fully agree! Along with updating the now very dated gif, I need to do some rework on the README to break things down to show more of the features and make it easier to navigate.

**Comment by MitMaro** [comment]
I did this about a month ago, and didn't even know there was an issue for it. :laughing:
