### ISSUE TITLE
Support "Home" and "End" keys during edit

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#284]
When editing a commit, support using the "Home" and "End" keys to move to the start and end of the edit content.

**Comment by meldron** [comment]
I wanted to look into this issue, but Isn't this already impelemtend with https://github.com/MitMaro/git-interactive-rebase-tool/commit/26f6366070d7427eb1228e5ff7870e0b5f47a554?

**Comment by MitMaro** [comment]
I meant to close this issue after that was merged...

Thanks for letting me know that I forgot to reference and close the issue!
