### ISSUE TITLE
Provide version information in binary

### ISSUE THREAD

**Issue by homeworkprod** [MitMaro/git-interactive-rebase-tool#29]
Thanks for the nice tool.

I got confused by `.deb` release for v0.4.0 whose filename is `git-interactive-rebase-tool_0.3.0_amd64.deb` (the same as for the v0.3.0).

The binary itself does neither support the `--version` command-line option nor seem to tell its version somewhere else.

So after having downloaded a file `git-interactive-rebase-tool_0.3.0_amd64.deb` its not clear which version it actually is, both before and after installation.

I suggest to provide the common `--version` option and, if possible, correct the `.deb` filename of the v0.4.0 release retroactively.

**Comment by MitMaro** [comment]
The version number in the filename was wrong in the release and I've corrected it. Thanks for letting me know!

I also agree that there should be a `--version` option.

**Comment by MitMaro** [comment]
Added Pull Request #30 that will add the `--version` option along with an alias to `-v`.

Thanks again for the suggestion!

**Comment by MitMaro** [comment]
Released version 0.5.0 with a new `.deb`. Just for good measure I also rebuilt and uploaded version 0.4.0.

**Comment by homeworkprod** [comment]
Great, thanks!

You might wanna keep in mind to think about a way to keep the version number in a constant or to pass it at build time or something so that it becomes more visible (rather than being somewhat buried) in the code base, easy to change in a central place, and hard to overlook when making new releases.

I'm not sufficiently familiar with Rust's tool chain and best practices yet, so I can't make an exact suggestion on how to do that.

**Comment by homeworkprod** [comment]
I hereby confirm that the CLI option of v0.5.0 works as expected for me. 👍

**Comment by MitMaro** [comment]
I was thinking it would be nice to read the version from the `Cargo.toml` file but I'm also fairly new to rust and still have to learn a few things.

**Comment by MitMaro** [comment]
Pull request #41 make it so the version number is pulled from the `Cargo.toml` file.

**Comment by homeworkprod** [comment]
Nice, thank you!

Will use your change as a reference on how to do that in my own tools in the future. Much appreciated.
