### ISSUE TITLE
Windows and/or git bash installation / support ?

### ISSUE THREAD

**Issue by jnachtigall** [MitMaro/git-interactive-rebase-tool#36]
I work at a Windows shop. Is Windows supported and are there installation packages? I know that `ripgrep` and `fd` have Windows executables as part of their CI builds.

Maybe relevant: The Windows issue of `rebase-editor` for this: https://github.com/sjurba/rebase-editor/issues/7 Which is what I use atm with the mentioned workaround.

**Comment by MitMaro** [comment]
A friend of mine did have a build made for Windows and it did work for him. I don't do a whole lot of Windows development these days.

There is nothing in the project that would explicitly break windows usage. It already conditionally uses [PDCurses](https://github.com/wmcbrine/PDCurses) on Windows, so as long as your environment supports that, it should work.

The biggest issue from my side is that I don't have access to a Windows computer, nor any knowledge on creating an installer. Last time I did anything like that for Windows, I was using Visual Studio 6, and now I'm pretty much full time Linux user. The only reason there is a MacOS build is that I still use a Mac at work and have an old machine kicking around to do the builds.

I would very much welcome a PR that either made changes to the project or added instructions on creating a windows installer. I may take a stab at it at some point, perhaps in a VM.

**Comment by jnachtigall** [comment]
Not sure how `fd` (https://github.com/sharkdp/fd#installation) or `rip-grep` (https://github.com/BurntSushi/ripgrep#installation) do it which have packages on each release. I guess there must be some kind of CI for automatically building rust packages for various platforms on each release.

I'll probably go down to using cargo and can report back so that you could add a word about windows later.

PS
As a side note, I am new to interactive rebase as a whole. And I wonder what this tools makes different then say `rebase-editor`. Maybe this could be in the README.

**Comment by MitMaro** [comment]
After 20+ attempts I think I successfully have a build working with Appveyor. It's not an installer, but it does build a `.exe` that should be usable. Feel free to give [the release](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/20) a try. You probable want `git-interactive-rebase-tool--x86_64-pc-windows-msvc.zip`.

@Gudahtt would you mind giving it a test on Windows?

**Comment by jnachtigall** [comment]
@MitMaro Thank you for your efforts, just quickly executing I think it is working:

![image](https://user-images.githubusercontent.com/3307404/36889963-7543a502-1dfc-11e8-91a4-5a96de51ee8b.png)

**Comment by Gudahtt** [comment]
@MitMaro Sure!

I've tested all four binaries, and they all seem to work. I've tested with Powershell and Git-Bash. It will open in a separate terminal window.

**Comment by jnachtigall** [comment]
> It will open in a separate terminal window.

That's actually a bit annoying that it popsup in another window instead of using the existing one.

**Comment by MitMaro** [comment]
I can't seem to figure out why this is happening. I will need to get a Windows VM running to try a few things.

**Comment by nickolay** [comment]
Is it just me or is scrolling a long list of commits in the separate popup window broken too? (Am I right in assuming the currently selected commit is simply scrolled into view on other OSes?)

**Comment by nickolay** [comment]
The "separate terminal window" issue (along with the lack of scrolling) was fixed for me simply by switching to `features = ["win32"]` (along with bumping the version to 0.16.0) from the default `win32a`, as documented here: https://github.com/ihalila/pancurses#pdcurses-windows-details

**Comment by MitMaro** [comment]
I've released [version 0.7.0](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/0.7.0). I'm hoping that this resolves the Windows problems. If it does not post a new issue and I will take another stab.
