### ISSUE TITLE
Force abort writes 'noop'

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#383]
(Working on the latest commit, 93012a2)

Force abort writes `noop` to the rebase file instead of truncating the file which causes Git to still update the `HEAD` ref (& current branch).

For example:

```bash
$ printf '%s\n' 'squash aaaaaaaa Some text' > foo.txt && target/release/interactive-rebase-tool foo.txt
$ cat foo.txt 
noop
$
```

Versus 1.2.1:

```bash
$ printf '%s\n' 'squash aaaaaaaa Some text' > foo.txt && target/release/interactive-rebase-tool foo.txt
$ cat foo.txt 
$ 

```

**Comment by MitMaro** [comment]
I wondered if there was a difference in an empty rebase file vs a noop. Thanks for doing the research, should be an easy fix.

**Comment by MitMaro** [comment]
Thanks for testing the development build and reporting the bug! The latest build (once it finishes) should no longer write a `noop` during abort.
