### ISSUE TITLE
2.0.0 release tag

### ISSUE THREAD

**Issue by SuperSandro2000** [MitMaro/git-interactive-rebase-tool#419]
Can you add a 2.0.0 release tag and remove the latest release tag? This would make the update process in nixpkgs and probably other distros a lot easier.

**Comment by MitMaro** [comment]
@SuperSandro2000 , I am hoping to get that done this week. :)

**Comment by MitMaro** [comment]
After some problems with the build, the new tag has been released. Thanks!
