### ISSUE TITLE
Squash (or other action) this and all below this point

### ISSUE THREAD

**Issue by kevdoran** [MitMaro/git-interactive-rebase-tool#438]
First, thank you for this awesome tool. It is essential on all development machines I use. This issue is an idea / feature request:

A common workflow for interactive rebase is to pick the first commit and squash all others into that single commit. Visual mode makes this fairly quick to achieve, but for a large branch it is still many commits to select and change.

A key shortcut for either "squash this commit and all commits below this point" would be useful. 

Suggestions: uppercase `S` or `<modifier-key>+s`

Whatever is decided upon for the action key, if it is based on the lowercase action key, then the same convention could be used for other commands. For example, `F: fixup this commit and and all commits below this`. This would also give an easy way to "undo", if one unintentionally hit `S` or `F`, they could then tap `P` to "reset" all commits.

**Comment by MitMaro** [comment]
> First, thank you for this awesome tool. It is essential on all development machines I use.

Thank you! Honestly, it's hearing about people using the tool that motivates me to continue the development.

**Comment by MitMaro** [comment]
I've added something that I think I will cover this use case. It's not exactly as requested, in that it will take a couple of extra keystrokes.

With #455 you can hit "End" or "Home" in visual mode to select all lines from the visual mode start to the top or bottom of the list and then select the action.


https://user-images.githubusercontent.com/177427/112725957-d9fc6900-8efd-11eb-9cc2-1d3cdd075140.mp4

**Comment by kevdoran** [comment]
That's great, thanks @MitMaro!
