### ISSUE TITLE
Help (?) is hard to read: Blue text on Black background

### ISSUE THREAD

**Issue by jnachtigall** [MitMaro/git-interactive-rebase-tool#46]
The left handside blue on black letters are hard to read:

![image](https://user-images.githubusercontent.com/3307404/37036156-0c583f3e-214f-11e8-9a58-3d0ceb20862d.png)

PS As a side note:
1. Also, to me as a `rebase` beginner (and I think that especially beginners might benefit from a great interactive tool like this) it was not clear that `w` / `W` means save and proceed. Not sure, but when using the node based `rebase-editor` I think it was clearer what each command / letter would do. Also,  `Immediately write/abort` sounded to me like a really strong action, where it just seems to mean that the "Do you really want to ..." question is overstepped.

**Comment by MitMaro** [comment]
I think I need to make the colors configurable.

The actual colors are determined by your terminal and will look different on each terminal. On my work Mac it looks like:

![screen shot 2018-03-06 at 10 54 39 am](https://user-images.githubusercontent.com/177427/37037528-1235ef36-212d-11e8-9324-486cf6399340.png)

And it looks differently on my personal Linux computer.

**Comment by MitMaro** [comment]
To your side note, thanks for the input! I can see how the current wording would be confusing if you are not used to interacting with the rebase using vim or a similar editor. There is definitely better wording I can use there. I've also been debating in the last little while removing the `W` and `Q` commands. I think hitting `wy` or `qy` are quicker once muscle memory is built up instead of `shift+w` and `shift-q`.

As my own side note:

Thanks for all the input in general! You've provided several great improvements, criticisms and provided me with the energy to do more with the tool.

**Comment by MitMaro** [comment]
Another side note, it might be worth looking at https://stackoverflow.com/a/31944618 as I think you will run into other terminal applications that will use that blue on black as well.

With terminal applications I don't actually get to choose the color that is used, I can just ask the terminal to write something in what it considers blue. You can see the [color selection in the code](https://github.com/MitMaro/git-interactive-rebase-tool/blob/master/src/window.rs#L25).

It is possible to completely redefine every color that is used, giving it an exact color, but that's often looked upon poorly as it deviates from the color scheme chosen by the user.

**Comment by MitMaro** [comment]
The upcoming version will allow all the colors to be customized.

**Comment by mrexodia** [comment]
I think a more sensible approach is to change the default on Windows. My guess is that everybody will have a bad experience on Windows right now. Why not change the default to white and allow the user to customize the color back to be a bad experience if they want to 🙂?

Commit here: https://github.com/mrexodia/git-interactive-rebase-tool/commit/4d76184298c87449c015800ecbb366e5ccfbcc70
