### ISSUE TITLE
help flag doesn't work

### ISSUE THREAD

**Issue by alok** [MitMaro/git-interactive-rebase-tool#52]
I installed this via `cargo install --git` and when I run it with the `--help` flag, I get:

```
Error opening file, -h
Reason: entity not found
```

**Comment by MitMaro** [comment]
That's very odd, `--help` should have worked. I want to confirm that you ran the command `interactive-rebase-tool --help`.

To help debug, can you provide:

* Try: `interactive-rebase-tool --version`, to see if it will print a version
* Try: `interactive-rebase-tool` if that will show `error: The following required arguments were not provided`.
* Output of `type interactive-rebase-tool` to ensure the install went as expected

**Comment by alok** [comment]
--version works correctly.

no arguments gives:

```
Must provide a filepath.

Usage: git-interactive <filepath>
```

type gives ~/.cargo/bin/interactive-rebase-tool, as expected.

**Comment by alok** [comment]
Turns out it was `v0.5.0`. The machine I tried this on had the older version.

**Comment by MitMaro** [comment]
Good to hear it was that simple! :)
