### ISSUE TITLE
Show help if there's spare screen space

### ISSUE THREAD

**Issue by alok** [MitMaro/git-interactive-rebase-tool#53]
At least in my case, there's often a bunch of unused screen real estate, and displaying the help menu (or changing the display of the `Actions:` bar at the bottom) would be nice. Sort of like [WordStar](https://en.wikipedia.org/wiki/WordStar#/media/File:Wordstar_Screenshot.png)

**Comment by alok** [comment]
Something like the vim git-rebase message could also be handy since it reminds me that commands are run top to bottom and that squash is melded into the commit *above* (which i have a weirdly large amount of trouble remembering).

**Comment by Rustin-Liu** [comment]
@MitMaro  Can I work on it?  I want to contributing.  I think this maybe is a great place to get started.

**Comment by MitMaro** [comment]
@Rustin-Liu Absolutely! Contributions are welcome!

**Comment by MitMaro** [comment]
Also, in case you missed it, if you get a PR up in October it can count towards the Hacktoberfest!

https://hacktoberfest.digitalocean.com/

**Comment by Rustin-Liu** [comment]
> Also, in case you missed it, if you get a PR up in October it can count towards the Hacktoberfest!
> 
> https://hacktoberfest.digitalocean.com/

Got it!   Thank you very much.

**Comment by Rustin-Liu** [comment]
Hey @MitMaro!
I want to show help in header, if window's height twice the help lines length.

But, now I am confused about how to design the layout.

I want declare a const variable in constants.rs.
_pub const HEADER_HELP_ITEM_LENGTH: i32 = 46; //  **W    Immediately write interactive rebase file** is the longest_

I want to use this const length to align the each help item.  I want to display three entries per line.  So the show help condition is window's height twice the help lines length and window's width three times HEADER_HELP_ITEM_LENGTH.

I think the final look like:
![image](https://user-images.githubusercontent.com/29879298/66700783-65446780-ed27-11e9-8aa2-d9d6b04c7837.png)

Do you think I can do this, do you have other solutions?

**Comment by Rustin-Liu** [comment]
> Hey @MitMaro!
> I want to show help in header, if window's height twice the help lines length.
> 
> But, now I am confused about how to design the layout.
> 
> I want declare a const variable in constants.rs.
> _pub const HEADER_HELP_ITEM_LENGTH: i32 = 46;_
> I want to use this const length to align the each help item. I want to display three entries per line. So the show help condition is window's height twice the help lines length and window's width three times HEADER_HELP_ITEM_LENGTH.
> 
> I think the final look like:
> ![image](https://user-images.githubusercontent.com/29879298/66700783-65446780-ed27-11e9-8aa2-d9d6b04c7837.png)
> 
> Do you think I can do this, do you have other solutions?

@MitMaro  ping~

**Comment by MitMaro** [comment]
Hey @Rustin-Liu , I missed your previous comment. Thanks for the ping!

I think it would be better to have the expanded help replace the existing help line that is on the bottom when there is room. With the help on the top, there would be a UI flicker when the screen is resized large enough to add the additional help.

As for the alignment with three items, I think that will be fairly difficult with the current setup. I would look into what the [GNU `nano`](https://www.nano-editor.org/) editor does for the help line for inspiration. However, unlike nano it would make sense to expand the number of help lines as there is available screen size.  It may be possible to use a constant width for each help item and add more items as the screen expands.

## Example

Done with a text editor so by no means a final idea.

![Screenshot from 2019-10-28 10-43-55](https://user-images.githubusercontent.com/177427/67681266-ee86ab80-f96f-11e9-953f-5c2de61d72f1.png)

## Nano
![Screenshot from 2019-10-28 10-20-22](https://user-images.githubusercontent.com/177427/67679715-aa45dc00-f96c-11e9-8285-fa8df6274d2c.png)

![Screenshot from 2019-10-28 10-20-40](https://user-images.githubusercontent.com/177427/67679714-aa45dc00-f96c-11e9-8ec1-bfa70d7a33e2.png)

**Comment by Rustin-Liu** [comment]
> Hey @Rustin-Liu , I missed your previous comment. Thanks for the ping!
> 
> I think it would be better to have the expanded help replace the existing help line that is on the bottom when there is room. With the help on the top, there would be a UI flicker when the screen is resized large enough to add the additional help.
> 
> As for the alignment with three items, I think that will be fairly difficult with the current setup. I would look into what the [GNU `nano`](https://www.nano-editor.org/) editor does for the help line for inspiration. However, unlike nano it would make sense to expand the number of help lines as there is available screen size. It may be possible to use a constant width for each help item and add more items as the screen expands.
> 
> ## Example
> Done with a text editor so by no means a final idea.
> 
> ![Screenshot from 2019-10-28 10-43-55](https://user-images.githubusercontent.com/177427/67681266-ee86ab80-f96f-11e9-953f-5c2de61d72f1.png)
> 
> ## Nano
> ![Screenshot from 2019-10-28 10-20-22](https://user-images.githubusercontent.com/177427/67679715-aa45dc00-f96c-11e9-8285-fa8df6274d2c.png)
> 
> ![Screenshot from 2019-10-28 10-20-40](https://user-images.githubusercontent.com/177427/67679714-aa45dc00-f96c-11e9-8ec1-bfa70d7a33e2.png)

Got it.  
I can try it.

But I have a problem about help item.  Do you mean we just display short description, help item not same to help page?

By the way, I finished my hacktobefest challenge. Thank you!

**Comment by MitMaro** [comment]
>  Do you mean we just display short description, help item not same to help page?

Yeah, I think a short description would be okay.

I haven't put much thought into this, so I am also open to other ideas. Feel free to send along some other concepts. And ping me if I don't respond in a couple days! :)

**Comment by MitMaro** [comment]
I've decided to completely remove the inline help in the next release. It had grown large enough that it was meaningless and there built-in help display is always a key press away.
