### ISSUE TITLE
Add supported Git versions to README

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#54]
A [comment](https://news.ycombinator.com/item?id=17497187) on HackerNews mentioned putting the supported Git versions in the README.

**Comment by nickolay** [comment]
Note that while README says Git 1.7.8+, only [2.6.0 supports the "drop" action](https://stackoverflow.com/a/35846275/1026), so while using git 1.9 from Apple I got:

> Unknown command: drop <...>
> Please fix this using 'git rebase --edit-todo'.

Not sure if it's worth the hassle to update the readme though..
