### ISSUE TITLE
Autoselect next item after picking an action?

### ISSUE THREAD

**Issue by alok** [MitMaro/git-interactive-rebase-tool#55]
This may be more personal preference, but I find that once I've picked an action for a commit (say squash), I almost always want to go down to the next one and select an action for it. Autoselecting the next item may be a better default?

**Comment by MitMaro** [comment]
Interesting idea and I really can see the use case. If I did add it I would put it behind a configuration option.

**Comment by MitMaro** [comment]
Implemented in #72 .

Thanks for the request! Apologies that it took so long to implement.

This will be released in version 0.7, that I am hoping to release today, or next week.
