### ISSUE TITLE
Visualize diff from rebase point

### ISSUE THREAD

**Issue by alok** [MitMaro/git-interactive-rebase-tool#57]
It's nice to be able to diff your current tree from what you're rebasing against, and a keybinding like `v` (for `v`iew) to run `git diff` would be helpful.

**Comment by MitMaro** [comment]
Were you thinking to see the currently selected commit? I don't know if showing the full diff from the rebase would be helpful, and if needed could easily be done through another shell.

I would like to add the output of `git show <selected-hash>` to the existing "Show commit information".
