### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#571]
This is a tracking issue for various documentation errors in the project that need updates.

- [ ] `diffIgnoreWhitespace` config has wrong description
- [ ] `diffShowWhitespace` config has wrong description
- [ ] `diff.interhunk_lines` is not a thing, and should be `diff.interHunkContext`

**Comment by l-e-e-l-a** [comment]
hi. would like to work on this. :D

**Comment by MitMaro** [comment]
@okleela pull requests are very much welcome! 🙂
