### ISSUE TITLE
Better integration with `git-absorb`

### ISSUE THREAD

**Issue by drahnr** [MitMaro/git-interactive-rebase-tool#575]
First of all, thanks for creating this. I am using it daily and I am very very happy using it in general :+1:

There is a small issue when using it in combination with `git-absorb`, which pre-marks staged hungs as fixups to other commits, which do not get parsed correctly.

If there is interest in handling `!fixup` prefixed commit messages to be pre-selected as fixup for the desired commit, that would be truely awesome. I can also create PR for that if there is interest in this feature.

**Comment by nickolay** [comment]
`git config --global rebase.autosquash true` works fine for me with `git absorb` and `sequence.editor = interactive-rebase-tool`

**Comment by drahnr** [comment]
The use case I had in mind is slightly different, I would prefer to see them pre-marked to be squashed, but not auto-squashed.

**Comment by MitMaro** [comment]
@drahnr , can you expand more on what you have in mind?

With an interactive rebase, `--autosquash` just marks commits with `fixup!` (and related) to be fixup-ed into the related commit automatically.

For example, this is what the rebase file looks like at the launch of the tool:

![Screen Shot 2021-11-24 at 10 52 13 AM](https://user-images.githubusercontent.com/177427/143255933-7a68a164-5df2-4d5e-839b-b1cf68e00786.png)

**Comment by drahnr** [comment]
Works as described with the `autoquash`-option. Thank you!
