### ISSUE TITLE
Oldest Supported Rust Compiler Version?

### ISSUE THREAD

**Issue by jgarte** [MitMaro/git-interactive-rebase-tool#585]
Hi, what is the oldest version of the rust compiler that is supported by this project?

**Comment by MitMaro** [comment]
The CI tests against the latest stable version for the build and tests. Releases use the latest stable version. Formatting and coverage reports use the latest nightly, but occasionally, it's locked to a past version.

The project uses Rust 2021, so at the moment Rust 1.56.0 at a minimum. But there isn't any guarantee that that won't change. I eventually plan to define a `rust-toolchain.toml`.

**Comment by jgarte** [comment]
@MitMaro I was able to build `git-interactive-rebase-tool` with rust [1.53.0](https://github.com/void-linux/void-packages/pull/34137).

I've been using this binary fine for over a week. WDYT might be broken?

**Comment by MitMaro** [comment]
Makes sense, as that looks like that is building from the 2.1.0 tag, which would build on older versions of Rust. As of https://github.com/MitMaro/git-interactive-rebase-tool/commit/788b327731f0344d675791ef6d24e3b7b5034adc the minimum version would have changed.

**Comment by jgarte** [comment]
> Makes sense, as that looks like that is building from the 2.1.0 tag, which would build on older versions of Rust. As of [788b327](https://github.com/MitMaro/git-interactive-rebase-tool/commit/788b327731f0344d675791ef6d24e3b7b5034adc) the minimum version would have changed.

Ohhh ok. Thanks for pointing that out. I didn't think about that fact ;)

**Comment by MitMaro** [comment]
Closing this issue. If there are any further questions, I can follow up here.
