### ISSUE TITLE
shell out to editor?

### ISSUE THREAD

**Issue by srl295** [MitMaro/git-interactive-rebase-tool#60]
i'm trying to drop 30k commits in a rebase ( `gh-pages` branch )… would be nice if i could (1)  exit out to my usual editor,  or even (2) run a command on the todo file, something like this:

- i hit `!`
- i see a prompt:  **Execute command on todofile:** with the default: ( assuming VISUAL=emacs)

> `$ emacs .git/rebase-merge/git-rebase-todo`

- if i hit Enter it will sublaunch `emacs ./git/rebase-merge/git-rebase-todo` and edit the file
- when editor exits, interactive-rebase-tool re-reads `git-rebase-todo` and shows it onscreen
- proceed with the session

one could run `sed` or something against the file.

**Comment by MitMaro** [comment]
Would a write file, without exit, followed by a reload work here instead? That way you can have any external process run on the git-rebase-todo file and wouldn't be limited to command line tools.

**Comment by srl295** [comment]
@MitMaro probably write file, sublaunch something, then reload on exit?

Also, vi-like, would be good to have something like this: `!emacs %` where `!` is the command char, and `%` is replaced with the filename.

**Comment by MitMaro** [comment]
Basic support for this was added in #79.

**Comment by nickolay** [comment]
FWIW, I decided against "(2) run a command on the todo file" because vim (and probably others) already implements this, so allowing to launch it lets one do this without reimplementing the line-editing facilities in this tool.

**Comment by MitMaro** [comment]
This has been fully implemented in #176
