### ISSUE TITLE
Add option for rewriting committish in messages

### ISSUE THREAD

**Issue by whymarrh** [MitMaro/git-interactive-rebase-tool#61]
(I'm not sure where this option would go right since there's no config yet.)

It'd be neat if there was an option to have references to commits in the commit messages rewritten when successfully rebased. For example, let's say we have the following commits:

```
commit 7567b3365d2c2f18379b8305a174c99bc9f634dc (HEAD -> master)
Date:   Sat Sep 8 21:00:25 2018 -0230

    3rd
    
    Refs bcc2868

commit bcc2868f126a0392576c5ac4d4612d7d069444c9
Date:   Sat Sep 8 21:00:03 2018 -0230

    2nd

commit 9aff63810b6b22fa7fc8825791b2491d4e750a88
Date:   Sat Sep 8 20:59:57 2018 -0230

    1st
```

When I rebase the 2nd and 3rd commits it would be useful if the 3rd commit's message could automagically have its reference to `bcc2868` updated to the new hash of the 2nd commit.

**Comment by MitMaro** [comment]
@whymarrh has the idea to inject `exec` commands to handle this. It would require adding the ability to input text.

**Comment by MitMaro** [comment]
Here is a sample script in Bash, though it's not fully tested.

```shell
action="$1"
# I would check action here, to ensure it was a fixup/squash/etc

original_hash="$2"

# read the git commit message subject and body
# Optionally you could read the whole message and replace hashes in the subject as well
subject="$(git show -s --format='format:%s' $original_hash)"
message="$(git show -s --format='format:%b' $original_hash)"
new_message="$message"
possible_hashes="$(grep -o '[0-9a-fA-F]\{5,\}')"

while IFS='\n' read -r hash; do
	if [[ "$original_hash" = $hash* ]]; then
		hash_len="${#hash}"
		new_hash="${original_hash:0:$hash_len}"
		new_message="${new_message,$hash,$new_hash}"
	fi
done <<< $hashes

if [[ "$message" != "$new_message" ]]; then
	git commit --amend --no-verify -m "${subject}\n${new_message}"
fi
```

**Comment by MitMaro** [comment]
@whymarrh , I've added the described hook/config option described above. That, along with the sample script above, I believe that provides the functionality you were looking for.

Apologies for taking so long on this feature, ultimately, it was something I could have implemented some time ago, as there wasn't anything blocking this feature.

Please let me know if this doesn't meet your needs, or something doesn't work as expected. Thanks!
