### ISSUE TITLE
Release Version 2.2.0

### ISSUE THREAD

**Issue by clarfonthey** [MitMaro/git-interactive-rebase-tool#623]
The last release was last April, but a lot of changes have been made to the project since then; perhaps at least a new patch release should be published to account for that.

Release checklist:

- [x] Update the release* workflows to include latest versions of Ubuntu, Debian (https://github.com/MitMaro/git-interactive-rebase-tool/pull/649)
- [x] Fix [documentation errors](https://github.com/MitMaro/git-interactive-rebase-tool/issues/571) (https://github.com/MitMaro/git-interactive-rebase-tool/pull/650)
- [x] Add supported platforms to the README (https://github.com/MitMaro/git-interactive-rebase-tool/pull/658) (https://github.com/MitMaro/git-interactive-rebase-tool/pull/661)
- [x] Test on Windows
- [x] Test on macOS
- [x] Test on Linux
- [x] Update CHANGELOG (https://github.com/MitMaro/git-interactive-rebase-tool/pull/653)
- [x] Bump Cargo.toml version number (https://github.com/MitMaro/git-interactive-rebase-tool/pull/662)
- [x] Update README to remove reference to development build (https://github.com/MitMaro/git-interactive-rebase-tool/pull/662)
- [x] Release crates to crates.io
- [x] Tag new release tag

Found issues:
- [x] Resize event flood causes render lag, needs a debounce (https://github.com/MitMaro/git-interactive-rebase-tool/pull/652)
- [x] Shift + ? not working on Windows (https://github.com/MitMaro/git-interactive-rebase-tool/pull/655)
- [x] ? key does not work during edit (https://github.com/MitMaro/git-interactive-rebase-tool/pull/656)
- [x] Home/end missing from diff help (https://github.com/MitMaro/git-interactive-rebase-tool/pull/657)
- [x] [External editor not receiving all inputs](https://github.com/MitMaro/git-interactive-rebase-tool/issues/659) (https://github.com/MitMaro/git-interactive-rebase-tool/pull/660)

**Comment by MitMaro** [comment]
👍🏼 I don't think there have been many user-facing changes in a while, as I have been rewriting a lot of the internals to support some of the more cool features that I would like to add (search, rebase preview/validation, etc).

However, there are probably significant performance improvements that would be worth releasing, and I also believe Homebrew had to patch the current release to support compiling in the newest Rust version.

**Comment by clarfonthey** [comment]
Yeah, that's also another big reason I asked for this, since I've been building the git version to make sure it works on the latest nightly.

**Comment by MitMaro** [comment]
I hope you don't mind, but I "stole" this issue to track the release of the next version. I am actively working on getting a new release out.

Thanks for the friendly push. :)

**Comment by MitMaro** [comment]
Testing complete, and release is ready to go. Found a few pretty bad bugs, but they have all been fixed. I should hopefully find some time next week to do the release!

**Comment by MitMaro** [comment]
I found some time after work today and posted the release. Version 2.2.0 has been published! Thanks again for the push!

**Comment by clarfonthey** [comment]
Thank you for the wonderful tool!
