### ISSUE TITLE
Fix macOS build

### ISSUE THREAD

**Issue by MitMaro** [MitMaro/git-interactive-rebase-tool#75]
The macOS build isn't building the correct binary, as it seems I'm building the mac-os version on Linux instead of macOS.

Thanks @jackharrhy for testing this for me.

**Comment by MitMaro** [comment]
@jackharrhy, I put up a new build. Mind trying it again?

**Comment by jay-hankins** [comment]
macOS user here. Been working fine for me.

**Comment by jackharrhy** [comment]
Also been working fine 🌮

**Comment by MitMaro** [comment]
I will close the issue then. Thanks @jay-hankins and @jackharrhy !
