### ISSUE TITLE
Add arm64 and armhf builds to release

### ISSUE THREAD

**Issue by ayufan** [MitMaro/git-interactive-rebase-tool#786]
Can you provide precompiled binaries for armhf and arm64? Those platforms are increasingly popular with Raspberry PIs, Apple M1 (you can run virtualised linux), etc.

Looking at the build scripts it seems that you could use `qemu-binfmt` support and `arm64/debian:...` docker images to compile for another arch on a existing runners.

If someone wants to compile binary via docker:

```bash
docker run -v "$PWD/arm64:/cargo" -it --rm arm64v8/rust:bullseye cargo install --root /cargo git-interactive-rebase-tool
docker run -v "$PWD/armhf:/cargo" -it --rm arm32v7/rust:bullseye cargo install --root /cargo git-interactive-rebase-tool
```

Or, just generic way for a current architecture:

```bash
docker run -v "$PWD/cargo:/cargo" -it --rm rust:bullseye cargo install --root /cargo git-interactive-rebase-tool
```

Take into account that this will take quite some time on RPI.

**Comment by MitMaro** [comment]
Thanks for the request!

I believe homebrew already provides a M1 binary, but not everyone uses homebrew, so I support getting a M1 binary as part of the release. And to your point, doesn't support other Arm systems.

I will eventually look into this, but until then, pull requests are welcome!

**Comment by MitMaro** [comment]
#879 partially addresses this issue, creating the latest release on macOS arm.

I would still like to add additional build targets for Linux-based ARM, and to add the builds to the full release workflow.

**Comment by glensc** [comment]
looking for debian-12 arm64 package

**Comment by MitMaro** [comment]
As of #917 Arm packages are built for Debian as well as armhf for Raspberry Pi.

Dev builds will be available on the [latest tag](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/latest) once the build complete.
