### ISSUE TITLE
Feature: Move to next line on key press

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#808]
I'm rebasing onto a branch that has 100 extra commits, so instead of me having to press `d` and arrow down sequentially, make `d` move automatically to the next item after press, so I could just hold the `d` key to repeat the action multiple times.

**Comment by MitMaro** [comment]
The problem with making something highly configurable, it's almost impossible to know all the configuration options and what they could be called.

There's a setting for that one already, but it's disabled by default.

Can you try to set [`autoSelectNext`](https://github.com/MitMaro/git-interactive-rebase-tool/blob/master/readme/customization.md#general) to true and see if that works?

```
git config --global interactive-rebase-tool.autoSelectNext true
```

**Comment by glensc** [comment]
thanks! didn't know it's configurable.

but seems even I myself need to wear it out as muscle memory has memorized the arrow down :D
