### ISSUE TITLE
OS X iTerm 2 keeps screen in scrollback buffer for every action

### ISSUE THREAD

**Issue by Dziman** [MitMaro/git-interactive-rebase-tool#86]
After tool usage if you scroll up in iTerm 2 you'll see screen 'snapshots' for each action
<img width="1876" alt="screen shot 2018-12-21 at 10 38 39 am" src="https://user-images.githubusercontent.com/102422/50358458-3ea20f80-050e-11e9-9460-0d7932fae23a.png">
Just in case here is settings regarding scrollback buffer:
<img width="941" alt="screen shot 2018-12-21 at 10 41 26 am" src="https://user-images.githubusercontent.com/102422/50358489-58435700-050e-11e9-91e2-507c46767208.png">

**Comment by MitMaro** [comment]
PR is merged. I'm working towards a 1.0.0 release and this change will be part of that. Thanks!
