### ISSUE TITLE
Add support for --update-ref

### ISSUE THREAD

**Issue by glensc** [MitMaro/git-interactive-rebase-tool#872]
https://adamj.eu/tech/2022/10/15/how-to-rebase-stacked-git-branches/

suggests to set the flag globally:

```
git config --global --add --bool rebase.updateRefs true
```

yet this breaks this tool:

```
✖ git rebase origin/main -i  
hint: Waiting for your editor to close the file... Invalid action: update-ref
error: There was a problem with the editor 'interactive-rebase-tool'.
```

please add support for the flag, and maybe (if needed) `update-ref` command type

```
$ git --version
git version 2.41.0
$ interactive-rebase-tool --version
interactive-rebase-tool 2.2.1 (2023-03-13)
```

**Comment by MitMaro** [comment]
Thanks for the issue!

[update-ref](https://github.com/MitMaro/git-interactive-rebase-tool/pull/801) support was added this past November, however, looking at that version number, it should be working for you.

Probably a bug in the parsing, let me take a look!

**Comment by glensc** [comment]
@MitMaro problem is not about `update-ref` rebase lines, but that `--update-ref` is set as a global option:

```
git config --global --add --bool rebase.updateRefs true
```

the editor is not even launched, aborts with error:

```
✖ git rebase origin/main -i  
hint: Waiting for your editor to close the file... Invalid action: update-ref
error: There was a problem with the editor 'interactive-rebase-tool'.
```

from my `~/.gitconfig` I find these lines:

```
[sequence]
    editor = interactive-rebase-tool
[interactive-rebase-tool]
    autoSelectNext = true
[rebase]
   updateRefs = true    
```

**Comment by glensc** [comment]
Update: seems 2.3.0 was released just 2 days ago:
- https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/2.3.0

so, that's why it's not yet in brew.

and can't run the file directly from downloads, killed as not from a verified developer

```
~/Downloads/macos-interactive-rebase-tool          
zsh: killed     ~/Downloads/macos-interactive-rebase-tool
```

so have to wait for brew update to test :)

**Comment by glensc** [comment]
Update2: brew update pr is here, but currently build failing:
- https://github.com/Homebrew/homebrew-core/pull/137013

**Comment by neersighted** [comment]
This feature was implemented in 2.3.0, and I have been using it myself with `rebase.updateRefs = true` for several months. I think this issue can be closed 😄

**Comment by MitMaro** [comment]
Thanks @neersighted ! Good to hear that it's been working for you over the past several months.

I will keep the issue open until @glensc can confirm that it works on their system (once 2.3.0 hits homebrew), just in case there is some odd edge case.

**Comment by glensc** [comment]
2.3.0 hit homebrew!

**Comment by glensc** [comment]
I can confirm 2.3.0 no longer gives the parse error!
