### ISSUE TITLE
Create SDKMAN package

### ISSUE THREAD

**Issue by quintesse** [MitMaro/git-interactive-rebase-tool#88]
Right now only Debian derivatives are supported, it would be nice to have an [SDKMAN](https://sdkman.io) package to easily support all Linux versions.

For more information about creating a package see: https://sdkman.io/vendors

(Btw, running Fedora I tried using Homebrew but that gave all kinds of problems besides Homebrew downloading and installing half the internet)

**Comment by MitMaro** [comment]
Thanks for the request.

I'm closing this in favor of #172 .

I would support this project being available in SDKMAN but as I am not a user of that particular package system, I don't have the energy to work on that myself.

If you want to do the initial work, please feel free to open a PR!
