### ISSUE TITLE
`Enter` and `Esc` keys cannot be assigned as custom keys in list view

### ISSUE THREAD

**Issue by canemacchina** [MitMaro/git-interactive-rebase-tool#934]
Hi, I used to have this configuration:
```
[interactive-rebase-tool]
	inputRebase = Enter
        inputAbort = Esc
```

suddenly, it stopped working.
Note that If I change that to, for example

```
[interactive-rebase-tool]
	inputRebase = m
        inputAbort = g
```
it works again (using `m` and `g`), so the problems are the special keys.
I'm on a Mac with M1 pro chip, on Sonoma 14.5, using zsh 5.9

I'm pretty sure I have the same problem on Linux too (I'm using Arch and latest zsh) but I can't check now

**Comment by MitMaro** [comment]
Thanks for the report!

Turns out that this a bug in how the `Esc` and `Enter` keys are handled in the list view. Those keys are being caught by the search input handling, even when the search isn't active.

Other special characters do work as expected.

Thankfully, it looks like it's an easy fix!

**Comment by MitMaro** [comment]
I'm planning to do a release soon, before then, there are some ["latest" builds](https://github.com/MitMaro/git-interactive-rebase-tool/releases/tag/latest) available.


Thanks again for the report!

**Comment by canemacchina** [comment]
No worry, I can wait for the fix! Thanks!

**Comment by ewjoachim** [comment]
Hello and thanks for your hard work ! In the event that it would be easy for you to release the fix for this, can I request you do ? It's a bit annoying, I've been using "Enter" for "write" for ages and my brain bugs everytime I need to remember to use W instead ^^' But only if it's not too much work, otherwise, I'll train my brain :)

**Comment by canemacchina** [comment]
Still no chance for a release to fix this bug? I had to move out from Git Interactive Rebase Tool and install the NPM package (rebase-editor) again because this bug is really annoying.
